config_hash: 3ae6951d92f9052c77e15a33a099afcfc25a7d5c509767a3b50aff9173b8ae48
dataset_dir: ./dataset
dataset_hash: 2681f8ac23347626b88d3489e90064828f52c2d4be97071c1d6a91f0db36da4c
environment:
    network: none
    read_only_root: false
    volumes:
        - read_only: true
          source: ./dataset
          target: /app/dataset
        - read_only: false
          source: .
          target: /app/project
model_hash: 4ef892ebab27ec7b68d1e5b77ba80d2bddf8013c1da08dd8c4762566fb28450d
model_output_dir: ./output
training_script: python3 train.py
